# Chapter 4 Lab

# üç∫ Open Brewery DB API Lab

Welcome to your next hands-on adventure with AI + data! In this lab, you‚Äôll tap into a **real-world API**, roll up your sleeves with **Python + regex**, and work alongside your AI coding companion to clean and analyze structured data.

---

## ü§ñ What You‚Äôll Do

You‚Äôll be working with the **[Open Brewery DB API](https://www.openbrewerydb.org/documentation/)** ‚Äîa free, public API serving up details about breweries in the United States. You'll get access to:

- üè∑Ô∏è Brewery names  
- üèôÔ∏è City locations  
- ‚òéÔ∏è Phone numbers  
- üåê Website URLs  
- üçª Brewery types

ChatGPT can recognize this API by name, so go ahead and prompt it directly! If you want to give your AI buddy more context, you can also [download the API docs](https://www.openbrewerydb.org/documentation/) and upload them into your chat.

---

## üß™ Your Tasks

Here‚Äôs what you‚Äôll ask your AI assistant (or do manually in a Jupyter Notebook):

### 1Ô∏è‚É£ Get brewery data from New York  
üîç Prompt your AI:  
> "Get the name, city, and phone number of the first 5 breweries in New York using the Open Brewery DB API."

---

### 2Ô∏è‚É£ Clean up phone numbers with regex  
üìû Format them all like:  

> +1-XXX-XXX-XXXX


üîç Prompt your AI:  
> "Format the phone numbers using regex so they all follow the format +1-XXX-XXX-XXXX. Leave blank if the number is missing or malformed."

---

### 3Ô∏è‚É£ Extract website domain names  
üåê Use regex to remove `http://`, `https://`, and any trailing `/`.

üîç Prompt your AI:  
> "Extract the domain name from each brewery‚Äôs website URL using regex. Strip off http://, https://, and any trailing slashes."

---

## üß∞ Tools You‚Äôll Use

- üß† ChatGPT (or another AI coding companion)
- üß™ Jupyter Notebook
- üêç Python (with `requests`, `pandas`, and `re` libraries)

---

## üèÅ Let‚Äôs Get Brewing!

Once you're done, you‚Äôll have a clean, formatted DataFrame with:
- Brewery name ‚úÖ  
- City ‚úÖ  
- Formatted phone ‚úÖ  
- Website domain ‚úÖ

**Cheers to clean data and cold beer! üçª**

### 1Ô∏è‚É£ Get brewery data from New York

In [1]:
# Prompt:
# ‚ÄúWrite a Python script to fetch the first 5 breweries in New York using the Open Brewery DB API. Return a pandas DataFrame with columns for name, city, and phone.‚Äù
# Code:
import requests
import pandas as pd

url = "https://api.openbrewerydb.org/v1/breweries?by_state=new_york&per_page=5"
response = requests.get(url)

if response.status_code == 200:
    data = response.json()
    df = pd.DataFrame(data)
    df = df[["name", "city", "phone"]]
    display(df)
else:
    print(f"Error: {response.status_code} - {response.text}")

                       name            city       phone
0  12 Gates Brewing Company   Williamsville  7169066600
1          16 Stone Brewpub  Holland Patent  3158658500
2    1940's Brewing Company        Holbrook  6315334838
3     2 Way Brewing Company          Beacon  8452027334
4       212 Brewing Company       Davenport  2123779050


### 2Ô∏è‚É£ Clean up phone numbers with regex

In [2]:
# Prompt:
# ‚ÄúTake the phone column from the DataFrame and format each number as +1-XXX-XXX-XXXX using regex. Leave blank if the number is missing or malformed.‚Äù
# Code:
import re

def format_phone(phone):
    digits = re.sub(r"\D", "", str(phone))
    return f"+1-{digits[:3]}-{digits[3:6]}-{digits[6:]}" if len(digits) == 10 else ""

df["formatted_phone"] = df["phone"].apply(format_phone)
display(df[["name", "formatted_phone"]])

                       name  formatted_phone
0  12 Gates Brewing Company  +1-716-906-6600
1          16 Stone Brewpub  +1-315-865-8500
2    1940's Brewing Company  +1-631-533-4838
3     2 Way Brewing Company  +1-845-202-7334
4       212 Brewing Company  +1-212-377-9050

### 3Ô∏è‚É£ Extract website domain names

In [4]:
# Prompt:
# ‚ÄúAdd a column to the DataFrame that extracts only the domain name from website_url using regex. Remove http://, https://, and any trailing slashes.‚Äù
# Code:
# Add website column from original data if not already included
df["website_url"] = [b.get("website_url", "") for b in data]

def extract_domain(url):
    return re.sub(r"https?://", "", str(url)).strip("/")

df["domain"] = df["website_url"].apply(extract_domain)
display(df[["name", "domain"]])

                       name                       domain
0  12 Gates Brewing Company       www.12gatesbrewing.com
1          16 Stone Brewpub       www.16stonebrewpub.com
2    1940's Brewing Company  www.1940sbrewingcompany.com
3     2 Way Brewing Company   www.2waybrewingcompany.com
4       212 Brewing Company                         None